<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>icon\MtcTs001.ico</ApplicationIcon>
    <FileVersion>1.0.0.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="publish\**" />
    <EmbeddedResource Remove="publish\**" />
    <None Remove="publish\**" />
  </ItemGroup>


  <ItemGroup>
    <Reference Include="LibUsbDotNet">
      <HintPath>C:\src\JR_MTC\JR_MTC\LibUsbDotNet.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>